//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    
    public partial class SP_FindLast_Result1
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string ServTitle { get; set; }
        public string SecTitle { get; set; }
        public string Dr_Name { get; set; }
        public string VisitDate { get; set; }
        public string VisitTime { get; set; }
    }
}
