//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string NameAndFamily { get; set; }
        public string Mail { get; set; }
        public string Mob { get; set; }
        public Nullable<int> RoleID { get; set; }
        public byte[] img { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
