//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Reception
    {
        public int ID { get; set; }
        public int DocID { get; set; }
        public Nullable<int> PatID { get; set; }
        public int ServID { get; set; }
        public int SecID { get; set; }
        public string VisitTime { get; set; }
        public string VisitDate { get; set; }
    
        public virtual Tbl_Doctor Tbl_Doctor { get; set; }
        public virtual Tbl_Patient Tbl_Patient { get; set; }
        public virtual Tbl_Section Tbl_Section { get; set; }
        public virtual Tbl_Service Tbl_Service { get; set; }
    }
}
