//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Patient()
        {
            this.Tbl_Pat_Images = new HashSet<Tbl_Pat_Images>();
            this.Tbl_Reception = new HashSet<Tbl_Reception>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string adrs { get; set; }
        public string mobile { get; set; }
        public string Ncode { get; set; }
        public Nullable<int> CountOfPictures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pat_Images> Tbl_Pat_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reception> Tbl_Reception { get; set; }
    }
}
