//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_PatientWithImages
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string adrs { get; set; }
        public string mobile { get; set; }
        public string Ncode { get; set; }
        public byte[] Image { get; set; }
    }
}
