//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VisitTime
    {
        public string SecTitle { get; set; }
        public string family { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public string TimeNobat { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TimeResidan { get; set; }
        public string Expr1 { get; set; }
        public string ServTitle { get; set; }
        public string DocNo { get; set; }
        public Nullable<bool> select { get; set; }
    }
}
